### ISSUE TITLE
Support for UMIs

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/digestiflow-demux#3]
UMIs should be configured by the Demux Web user and setting `demux_reads`.

For starters, we will only support this on a per-flow cell setting based on `demux_reads`.

`<num>`M will be used for molecular barcoding. In the case that the sequence is ligated to the template, `bcl2fastq2` should be able to handle this. If the UMI is an index read, we will have to fall back to Picard.

**Comment by messersc** [comment]
As discussed, this issue is more about user-configurable bases masks (`demux_reads`) than the use case with UMIs going to a separate fastq, as this was possible before with picard if set up correctly.

https://github.com/bihealth/digestiflow-demux/pull/7 adds the capability to parse `demux_reads` and match it with `planned_reads`, check it for consistency and return a bases mask for bcl2fastq2 (e.g. `y100,I8`) or picard (`100T8B`).
